import {
  formatVietnamMonthYear,
  formatVietnamTime,
  getVietnamDateParts,
  getVietnamDayOrdinal,
  isSameVietnamDay,
} from './dateTime';

const DEFAULT_SETTINGS = {
  language: 'vi',
  currency: 'VND',
  appearance: 'light',
  amountDisplay: 'symbol',
  dateFormat: 'dd/MM/yyyy',
  weekStartsOn: 'monday',
  firstDayOfMonth: 1,
  firstMonthOfYear: 1,
  reportRange: '3_months',
  overviewMode: 'balance',
  excludeFromReportDefault: false,
  dailyReminder: true,
};

const LANGUAGE_TO_LOCALE = {
  vi: 'vi-VN',
  en: 'en-US',
};

const DICTIONARY = {
  vi: {
    tab_home: 'Trang chủ',
    tab_reports: 'Báo cáo',
    tab_smart: 'Góc thông minh',
    tab_wallets: 'Ví',
    tab_profile: 'Cá nhân',
    loading_data: 'Đang tải dữ liệu tài chính thông minh...',
    greeting: 'Xin chào, {name}',
    home_title: 'Trung tâm điều khiển tài chính',
    total_balance: 'Tổng số dư',
    forecast_overspend: 'Dự báo cho thấy tháng này có thể bội chi khoảng {amount}.',
    forecast_surplus: 'Dự báo cuối tháng còn dư khoảng {amount}.',
    income_mtd: 'Thu trong tháng',
    expense_mtd: 'Chi trong tháng',
    quick_actions: 'Thao tác nhanh',
    quick_add_income: 'Thêm thu',
    quick_add_expense: 'Thêm chi',
    quick_budget: 'Góc thông minh',
    quick_wallets: 'Ví tiền',
    wallet_stack: 'Danh sách ví',
    open_reports: 'Mở báo cáo',
    budget_overview: 'Ngân sách tháng',
    recent_transactions: 'Giao dịch gần đây',
    total_wallets: 'Số ví',
    active_budgets: 'Ngân sách',
    smart_corner: 'Góc thông minh',
    smart_corner_desc: 'Hệ thống đang theo dõi nhịp chi tiêu và đưa ra cảnh báo sớm cho bạn.',
    smart_corner_action: 'Xem phân tích',
    smart_title: 'Góc thông minh',
    smart_subtitle: 'Theo dõi điểm tài chính, dự báo cuối tháng và các cảnh báo cần xử lý trước.',
    smart_score_label: 'Điểm tài chính',
    smart_health_label: 'Trạng thái',
    smart_top_category: 'Danh mục chi nhiều nhất',
    smart_budget_pressure_title: 'Ngân sách cần chú ý',
    smart_anomaly_title: 'Tín hiệu nổi bật',
    smart_forecast_title: 'Dự báo tháng này',
    smart_daily_cap_title: 'Chi bình quân/ngày',
    smart_drilldown: 'Mở giao dịch',
    over_limit_short: 'Vượt mức',
    near_limit_short: 'Sắp chạm trần',
    transaction_feed: 'Giao dịch ngày {date}',
    no_transaction_day: 'Ngày này chưa có giao dịch',
    no_transaction_day_desc: 'Hãy thêm giao dịch để hệ thống dự báo học được thói quen chi tiêu đầy đủ hơn.',
    add_new_transaction: 'Thêm giao dịch mới',
    notification_budget_over: 'Ngân sách {category} đã vượt mức',
    notification_budget_over_desc: 'Chi tiêu tháng này đã vượt hạn mức hiện tại. Bạn nên kiểm tra lại danh mục này.',
    notification_budget_near: 'Ngân sách {category} sắp chạm trần',
    notification_budget_near_desc: 'Tốc độ chi hiện tại cho thấy danh mục này có thể chạm mức giới hạn trước cuối tháng.',
    notification_forecast_risk: 'Dự báo phát hiện áp lực dòng tiền',
    notification_forecast_risk_desc: 'Tổng chi dự kiến đang cao hơn thu nhập khoảng {amount}.',
    notification_pattern_scan: 'Phân tích hành vi',
    notification_insight: 'Insight',
    notification_reminder: 'Nhắc nhở',
    notification_no_transaction: 'Ngày đang xem chưa có giao dịch mới',
    notification_no_transaction_desc: 'Nếu bạn đã phát sinh chi tiêu vào {date}, hãy thêm ngay để báo cáo chính xác hơn.',
    notification_income_captured: 'Đã ghi nhận khoản thu: {title}',
    notification_expense_captured: 'Đã ghi nhận khoản chi: {title}',
    notification_captured_desc: 'Một giao dịch {amount} vừa được đồng bộ vào sổ thu chi.',
    category_income: 'Thu',
    category_expense: 'Chi',
    reports_title: 'Phân tích và dự báo',
    reports_subtitle: 'Phân tích tài chính trong {monthYear} dựa trên dữ liệu giao dịch hiện tại.',
    month_expense: 'Chi trong tháng',
    projected_close: 'Dự báo cuối tháng',
    projected_surplus: 'Dư dự kiến',
    remaining_days: 'Ngày còn lại',
    monthly_budget_map: 'Bản đồ ngân sách tháng',
    create_budget: 'Tạo ngân sách',
    over_limit_month: 'Đã vượt ngân sách tháng này',
    near_limit: 'Sắp chạm giới hạn',
    remaining_amount: 'Còn lại {amount}',
    expense_ranking: 'Xếp hạng chi tiêu',
    no_expense_month: 'Tháng này chưa có chi tiêu nào.',
    new_smart_transaction: 'Thêm giao dịch thông minh',
    edit_transaction: 'Chỉnh sửa giao dịch',
    expense: 'Chi tiêu',
    income: 'Thu nhập',
    transaction_title: 'Tên giao dịch',
    smart_suggest: 'Gợi ý thông minh: danh mục phù hợp là {category}',
    amount: 'Số tiền',
    note: 'Ghi chú',
    wallet: 'Ví',
    category: 'Danh mục',
    validation_title: 'Vui lòng nhập tên giao dịch.',
    validation_amount: 'Vui lòng nhập số tiền lớn hơn 0.',
    validation_wallet_category: 'Vui lòng chọn ví và danh mục.',
    update_transaction: 'Lưu thay đổi',
    create_transaction: 'Tạo giao dịch',
    input_amount: 'Nhập số tiền',
    live_amount: 'Số tiền hiện tại',
    use_amount: 'Dùng số tiền này',
    profile_role: 'Người dùng ứng dụng quản lý thu chi',
    account_overview: 'Tổng quan tài khoản',
    wallet_count: 'Số ví đang quản lý',
    income_transactions: 'Giao dịch thu nhập',
    expense_transactions: 'Giao dịch chi tiêu',
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    currency: 'Tiền tệ',
    reset_demo: 'Khôi phục dữ liệu mẫu',
    wallets_title: 'Quản lý ví',
    wallets_subtitle: 'Toàn bộ nguồn tiền hiện có của bạn được gom về một nơi.',
    current_assets: 'Tổng tài sản hiện tại',
    synced_in_app: 'Đồng bộ trong ứng dụng',
    notifications_title: 'Thông báo',
    notifications_new: 'Bạn có {count} thông báo mới cần xem.',
    notifications_empty_subtitle: 'Mọi cập nhật thu chi gần đây sẽ hiện ở đây.',
    notifications_helper: 'Chạm vào từng thẻ để đánh dấu đã đọc.',
    notifications_all_read: 'Tất cả thông báo đã được đọc.',
    mark_all_read: 'Đọc tất cả',
    no_notifications: 'Chưa có thông báo nào',
    no_notifications_desc: 'Khi có nhắc ngân sách, biến động số dư hoặc giao dịch mới, hệ thống sẽ hiển thị tại đây.',
    ai_pulse: 'Trợ lý tài chính',
    smart_signals: 'Tín hiệu tài chính thông minh tháng này',
    score: 'điểm',
    score_excellent: 'Kiểm soát rất tốt',
    score_healthy: 'Nhịp chi tiêu ổn định',
    score_tuning: 'Cần tinh chỉnh',
    score_risk: 'Có rủi ro cần chú ý',
    run_rate: 'Mức chi bình quân',
    forecast: 'Dự báo',
    cashflow_pressure: 'Áp lực dòng tiền',
    budget_pressure: 'Áp lực ngân sách',
    forecast_stable: 'Dự báo ổn định',
    forecast_risk_desc: 'Nếu giữ nhịp chi hiện tại, tổng chi có thể cao hơn thu khoảng {amount}.',
    forecast_budget_desc: 'Mức chi dự kiến có thể vượt tổng ngân sách đang đặt.',
    forecast_stable_desc: 'Nếu giữ nhịp hiện tại, bạn có thể còn dư khoảng {amount} vào cuối tháng.',
    category_concentration: 'Danh mục chiếm tỷ trọng cao',
    category_concentration_desc: '{category} đang chiếm khoảng {percent}% tổng chi trong tháng.',
    coach_notes: 'Gợi ý từ trợ lý',
    next_moves: 'Bước nên làm tiếp theo',
    spike_detected: 'Phát hiện khoản chi bất thường',
    spike_detected_desc: '{title} đang cao hơn đáng kể so với mặt bằng chi tiêu thường thấy trong tháng.',
    no_major_anomaly: 'Không có biến động lớn',
    no_major_anomaly_desc: 'Nhịp chi tiêu của bạn hiện vẫn khá ổn định.',
    tip_cutting: 'Nếu giảm {category} khoảng 15%, bạn có thể tiết kiệm gần {amount} trong tháng này.',
    tip_daily_cap: 'Để giữ nhịp chi ổn hơn, bạn nên giới hạn chi linh hoạt khoảng {amount} cho mỗi ngày còn lại.',
    tip_budget_pressure: '{category} đang là danh mục áp lực nhất, xử lý trước sẽ kéo điểm tài chính lên nhanh nhất.',
    tip_budget_close: '{category} đã gần chạm trần, nên cân nhắc kỹ trước khi phát sinh thêm trong danh mục này.',
    tip_surplus: 'Bạn vẫn đang giữ được thặng dư, chuyển phần dư sang tiết kiệm ngay sẽ an toàn hơn.',
    today_at: 'Hôm nay, {time}',
    yesterday_at: 'Hôm qua, {time}',
    transaction_group_income: 'Danh sách khoản thu tháng {month}',
    transaction_group_expense: 'Danh sách khoản chi tháng {month}',
    search_placeholder: 'Tìm giao dịch, ví, danh mục...',
    search_no_results: 'Không tìm thấy giao dịch nào phù hợp.',
    search_results_count: 'Tìm thấy {count} kết quả',
    export_report: 'Xuất báo cáo',
    export_report_content: 'Báo cáo tài chính tháng {monthYear}\n\n- Tổng thu: {income}\n- Tổng chi: {expense}\n- Dư kiến: {surplus}\n\nChi tiêu nhiều nhất: {topCategory}\nĐiểm tài chính: {score}/100 ({label})',
    savings_goals: 'Mục tiêu tiết kiệm',
    savings_current: 'Đã có: {amount}',
    savings_target: 'Mục tiêu: {amount}',
    add_savings_goal: 'Thêm mục tiêu',
    edit_savings_goal: 'Sửa mục tiêu',
    savings_goal_name: 'Tên mục tiêu',
    savings_goal_amount: 'Số tiền cần tiết kiệm',
    savings_delete_confirm: 'Xóa mục tiêu này?',
    settings_screen_title: 'Cài đặt',
    back: 'Quay lại',
    settings_display: 'Hiển thị',
    appearance: 'Giao diện ứng dụng',
    appearance_light: 'Sáng',
    appearance_dark: 'Tối',
    appearance_auto: 'Tự động',
    settings_system: 'Hệ thống',
    setting_money_style: 'Kiểu hiển thị số tiền',
    setting_date_format: 'Định dạng thời gian',
    setting_week_start: 'Chọn ngày đầu tuần',
    setting_first_day_month: 'Đặt ngày đầu tiên của tháng',
    setting_first_month_year: 'Chọn tháng đầu tiên của năm',
    setting_report_range: 'Thiết lập khoảng thời gian báo cáo',
    setting_overview_mode: 'Chế độ hiển thị Tổng quan',
    setting_exclude_reports: 'Không tính vào báo cáo',
    setting_daily_reminder: 'Nhắc thêm giao dịch hằng ngày',
    setting_exclude_reports_desc: 'Bật tùy chọn này để giao dịch mới có thể được đánh dấu bỏ qua trong phần báo cáo.',
    setting_daily_reminder_desc: 'Ứng dụng sẽ nhắc bạn ghi lại thu chi mỗi ngày để báo cáo đầy đủ hơn.',
    money_style_symbol: 'Ký hiệu tiền tệ',
    money_style_code: 'Mã tiền tệ',
    week_monday: 'Thứ hai',
    week_sunday: 'Chủ nhật',
    report_range_3_months: 'Trong 3 tháng tiếp theo',
    report_range_6_months: 'Trong 6 tháng tiếp theo',
    report_range_12_months: 'Trong 12 tháng tiếp theo',
    overview_mode_balance: 'Hiện theo số dư',
    overview_mode_flow: 'Hiện thu và chi',
    option_month_1: 'Tháng Một',
    option_month_4: 'Tháng Tư',
    option_month_7: 'Tháng Bảy',
    option_month_10: 'Tháng Mười',
    choose_option: 'Chọn một tùy chọn',
    close: 'Đóng',
    settings_reset_card: 'Dữ liệu mẫu',
    settings_reset_desc: 'Khôi phục toàn bộ dữ liệu demo ban đầu nếu bạn muốn quay về trạng thái mặc định.',
    data_portability: 'Xuất / nhập dữ liệu',
    data_portability_desc: 'Xuất toàn bộ ví, ngân sách, giao dịch ra CSV hoặc nhập lại từ file CSV đã xuất trước đó.',
    export_csv: 'Xuất CSV',
    import_csv: 'Nhập CSV',
    export_csv_success: 'Đã tạo file CSV để chia sẻ.',
    import_csv_success: 'Đã nhập dữ liệu từ CSV.',
    import_csv_failed: 'Không thể nhập file CSV này.',
  },
  en: {
    tab_home: 'Home',
    tab_reports: 'Reports',
    tab_smart: 'Smart',
    tab_wallets: 'Wallets',
    tab_profile: 'Profile',
    loading_data: 'Loading smart finance data...',
    greeting: 'Hello, {name}',
    home_title: 'Finance command center',
    total_balance: 'Total balance',
    forecast_overspend: 'Forecast projects a monthly overspend of about {amount}.',
    forecast_surplus: 'Projected month-end surplus is about {amount}.',
    income_mtd: 'Income this month',
    expense_mtd: 'Expense this month',
    quick_actions: 'Quick actions',
    quick_add_income: 'Add income',
    quick_add_expense: 'Add expense',
    quick_budget: 'Smart corner',
    quick_wallets: 'Wallets',
    wallet_stack: 'Wallet stack',
    open_reports: 'Open reports',
    budget_overview: 'Monthly budgets',
    recent_transactions: 'Recent transactions',
    total_wallets: 'Wallets',
    active_budgets: 'Budgets',
    smart_corner: 'Smart corner',
    smart_corner_desc: 'The app is watching spending rhythm and surfacing early warnings for you.',
    smart_corner_action: 'Open analytics',
    smart_title: 'Smart corner',
    smart_subtitle: 'Track your money score, month-end forecast, and the next warnings to handle.',
    smart_score_label: 'Money score',
    smart_health_label: 'Status',
    smart_top_category: 'Top spending category',
    smart_budget_pressure_title: 'Budget to watch',
    smart_anomaly_title: 'Key signal',
    smart_forecast_title: 'This month forecast',
    smart_daily_cap_title: 'Average per day',
    smart_drilldown: 'Open transactions',
    over_limit_short: 'Over limit',
    near_limit_short: 'Near cap',
    transaction_feed: 'Transactions on {date}',
    no_transaction_day: 'No transaction on this day yet',
    no_transaction_day_desc: 'Add a transaction so the forecast engine can learn from a fuller spending pattern.',
    add_new_transaction: 'Add new transaction',
    notification_budget_over: 'Budget exceeded in {category}',
    notification_budget_over_desc: 'Monthly spend has moved above the current limit, so this category needs immediate review.',
    notification_budget_near: '{category} is close to its ceiling',
    notification_budget_near_desc: 'The current run rate suggests this category may hit its cap before month-end.',
    notification_forecast_risk: 'Forecast sees cashflow pressure',
    notification_forecast_risk_desc: 'Projected expense is pacing above income by about {amount}.',
    notification_pattern_scan: 'Pattern scan',
    notification_insight: 'Insight',
    notification_reminder: 'Reminder',
    notification_no_transaction: 'No transaction logged for the selected day',
    notification_no_transaction_desc: 'If you spent money on {date}, add it now to keep forecasts accurate.',
    notification_income_captured: 'Income captured: {title}',
    notification_expense_captured: 'Expense captured: {title}',
    notification_captured_desc: 'A {amount} transaction was just synced into your ledger.',
    category_income: 'Income',
    category_expense: 'Expense',
    reports_title: 'Analytics + Forecast',
    reports_subtitle: 'Monthly intelligence for {monthYear}, powered by your current transaction flow.',
    month_expense: 'Month expense',
    projected_close: 'Projected close',
    projected_surplus: 'Projected surplus',
    remaining_days: 'Remaining days',
    monthly_budget_map: 'Monthly budget map',
    create_budget: 'Create budget',
    over_limit_month: 'Over limit this month',
    near_limit: 'Close to limit',
    remaining_amount: '{amount} remaining',
    expense_ranking: 'Expense ranking',
    no_expense_month: 'No expense activity in this month yet.',
    new_smart_transaction: 'New smart transaction',
    edit_transaction: 'Edit transaction',
    expense: 'Expense',
    income: 'Income',
    transaction_title: 'Transaction title',
    smart_suggest: 'Smart detect suggests category: {category}',
    amount: 'Amount',
    note: 'Note',
    wallet: 'Wallet',
    category: 'Category',
    validation_title: 'Please add a transaction title.',
    validation_amount: 'Please enter an amount greater than zero.',
    validation_wallet_category: 'Please choose a wallet and category.',
    update_transaction: 'Update transaction',
    create_transaction: 'Create transaction',
    input_amount: 'Input amount',
    live_amount: 'Live amount',
    use_amount: 'Use amount',
    profile_role: 'Personal finance app user',
    account_overview: 'Account overview',
    wallet_count: 'Wallets managed',
    income_transactions: 'Income transactions',
    expense_transactions: 'Expense transactions',
    settings: 'Settings',
    language: 'Language',
    currency: 'Currency',
    reset_demo: 'Reset demo data',
    wallets_title: 'Wallet management',
    wallets_subtitle: 'All your available money sources are gathered in one place.',
    current_assets: 'Current total assets',
    synced_in_app: 'Synced in app',
    notifications_title: 'Notifications',
    notifications_new: 'You have {count} new notifications to review.',
    notifications_empty_subtitle: 'Recent money updates will appear here.',
    notifications_helper: 'Tap each card to mark it as read.',
    notifications_all_read: 'All notifications have been read.',
    mark_all_read: 'Mark all read',
    no_notifications: 'No notifications yet',
    no_notifications_desc: 'Budget reminders, balance changes, and new transactions will appear here.',
    ai_pulse: 'AI Finance Pulse',
    smart_signals: 'Smart money signals for this month',
    score: 'score',
    score_excellent: 'Excellent control',
    score_healthy: 'Healthy rhythm',
    score_tuning: 'Needs tuning',
    score_risk: 'Risk detected',
    run_rate: 'Run rate',
    forecast: 'Forecast',
    cashflow_pressure: 'Cashflow pressure',
    budget_pressure: 'Budget pressure',
    forecast_stable: 'Forecast stable',
    forecast_risk_desc: 'At the current pace, expenses may finish above income by {amount}.',
    forecast_budget_desc: 'Your projected spend is likely to move above the current budget stack.',
    forecast_stable_desc: 'At the current pace, you are on track to keep about {amount} as surplus.',
    category_concentration: 'Category concentration',
    category_concentration_desc: '{category} is taking {percent}% of monthly expense.',
    coach_notes: 'Coach notes',
    next_moves: 'Next best moves',
    spike_detected: 'Spike detected',
    spike_detected_desc: '{title} is much higher than your typical expense size this month.',
    no_major_anomaly: 'No major anomaly',
    no_major_anomaly_desc: 'Your expense pattern is staying close to its current baseline.',
    tip_cutting: 'Cutting {category} by 15% could save about {amount} this month.',
    tip_daily_cap: 'To stay flatter through month-end, try capping flexible spend near {amount} per remaining day.',
    tip_budget_pressure: 'Budget pressure is highest in {category}; this is the fastest place to recover your score.',
    tip_budget_close: '{category} is close to its limit, so new purchases there should be reviewed first.',
    tip_surplus: 'You are still ahead this month; moving the surplus into savings now will lock in progress.',
    today_at: 'Today, {time}',
    yesterday_at: 'Yesterday, {time}',
    transaction_group_income: 'Income list for month {month}',
    transaction_group_expense: 'Expense list for month {month}',
    search_placeholder: 'Search transactions, wallets, categories...',
    search_no_results: 'No matching transactions found.',
    search_results_count: 'Found {count} results',
    export_report: 'Export Report',
    export_report_content: 'Financial Report for {monthYear}\n\n- Total Income: {income}\n- Total Expense: {expense}\n- Projected Surplus: {surplus}\n\nTop Spending: {topCategory}\nFinance Score: {score}/100 ({label})',
    savings_goals: 'Savings Goals',
    savings_current: 'Current: {amount}',
    savings_target: 'Target: {amount}',
    add_savings_goal: 'Add Goal',
    edit_savings_goal: 'Edit Goal',
    savings_goal_name: 'Goal Name',
    savings_goal_amount: 'Target Amount',
    savings_delete_confirm: 'Delete this goal?',
    settings_screen_title: 'Settings',
    back: 'Back',
    settings_display: 'Display',
    appearance: 'App appearance',
    appearance_light: 'Light',
    appearance_dark: 'Dark',
    appearance_auto: 'Auto',
    settings_system: 'System',
    setting_money_style: 'Money display style',
    setting_date_format: 'Date format',
    setting_week_start: 'First day of week',
    setting_first_day_month: 'First day of month',
    setting_first_month_year: 'First month of year',
    setting_report_range: 'Report time range',
    setting_overview_mode: 'Overview display mode',
    setting_exclude_reports: 'Exclude from reports',
    setting_daily_reminder: 'Daily transaction reminder',
    setting_exclude_reports_desc: 'New transactions can be marked to stay out of analytics and report totals.',
    setting_daily_reminder_desc: 'The app will remind you to log daily income and expenses.',
    money_style_symbol: 'Currency symbol',
    money_style_code: 'Currency code',
    week_monday: 'Monday',
    week_sunday: 'Sunday',
    report_range_3_months: 'Next 3 months',
    report_range_6_months: 'Next 6 months',
    report_range_12_months: 'Next 12 months',
    overview_mode_balance: 'Show balance',
    overview_mode_flow: 'Show income and expense',
    option_month_1: 'January',
    option_month_4: 'April',
    option_month_7: 'July',
    option_month_10: 'October',
    choose_option: 'Choose an option',
    close: 'Close',
    settings_reset_card: 'Demo data',
    settings_reset_desc: 'Restore the original sample data if you want to return to the default state.',
    data_portability: 'Data portability',
    data_portability_desc: 'Export wallets, budgets, and transactions to CSV or import them back from a previously exported file.',
    export_csv: 'Export CSV',
    import_csv: 'Import CSV',
    export_csv_success: 'CSV file is ready to share.',
    import_csv_success: 'Data imported from CSV.',
    import_csv_failed: 'Unable to import this CSV file.',
  },
};

let formatterSettings = { ...DEFAULT_SETTINGS };

function interpolate(template, params = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key) => params[key] ?? '');
}

export function setAppPreferences(settings = {}) {
  formatterSettings = {
    ...DEFAULT_SETTINGS,
    ...settings,
  };
}

export function getAppPreferences() {
  return formatterSettings;
}

export function getCurrentLocale() {
  return LANGUAGE_TO_LOCALE[formatterSettings.language] || 'vi-VN';
}

export function t(key, params) {
  const language = formatterSettings.language in DICTIONARY ? formatterSettings.language : 'vi';
  const template = DICTIONARY[language][key] || DICTIONARY.vi[key] || key;
  return interpolate(template, params);
}

export function formatCurrency(value) {
  const amount = Number(value || 0);
  const currency = formatterSettings.currency || 'VND';
  const locale = getCurrentLocale();

  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
    currencyDisplay: formatterSettings.amountDisplay || 'symbol',
    minimumFractionDigits: currency === 'VND' ? 0 : 2,
    maximumFractionDigits: currency === 'VND' ? 0 : 2,
  }).format(amount);
}

export function formatSignedAmount(type, amount) {
  return `${type === 'income' ? '+' : '-'}${formatCurrency(amount)}`;
}

export function formatRelativeDate(dateValue) {
  const locale = getCurrentLocale();
  const diffDays = getVietnamDayOrdinal(new Date()) - getVietnamDayOrdinal(dateValue);
  const timeText = formatVietnamTime(dateValue, locale);

  if (diffDays === 0) {
    return t('today_at', { time: timeText });
  }

  if (diffDays === 1) {
    return t('yesterday_at', { time: timeText });
  }

  return `${formatDateBadge(dateValue)}, ${timeText}`;
}

export function formatDateBadge(dateValue) {
  const parts = getVietnamDateParts(dateValue);
  const pattern = formatterSettings.dateFormat || 'dd/MM/yyyy';
  const day = String(parts.day).padStart(2, '0');
  const month = String(parts.month + 1).padStart(2, '0');
  const year = String(parts.year);

  if (pattern === 'MM/dd/yyyy') {
    return `${month}/${day}/${year}`;
  }

  if (pattern === 'yyyy-MM-dd') {
    return `${year}-${month}-${day}`;
  }

  return `${day}/${month}/${year}`;
}

export function formatMonthYear(dateValue) {
  return formatVietnamMonthYear(dateValue, getCurrentLocale());
}

export function isSameCalendarDay(left, right) {
  return isSameVietnamDay(left, right);
}
